enquiry/enq/urls.py
from django.contrib import admin
from django.urls import path,include
from enq.views import *

urlpatterns = [
    path('home',DashBoard.as_view(),name="home"),
    path('listenquiry',Enquiry_list.as_view(),name="listenquiry"),
    path('createenquiry',Enquiry_Create.as_view(),name="createenquiry"),
    path('detailenquiry/<str:pk>',EnquiryDetail.as_view(),name="detailenquiry"),
    path('updateenquiry/<str:pk>',EnquiryUpdate.as_view(),name="updateenquiry"),
    path('deleteenquiry/<str:pk>',EnquiryDelete.as_view(),name="deleteenquiry"),
    path('followup',FollowUp.as_view(),name="followup"),
    path('followupdetails/<str:pk>',FollowUpDetail.as_view(),name="followupdetails"),
    path('searchdate',SearchDate.as_view(),name="searchdate"),
    path('report/>',ReportUpdate.as_view(),name="report"),
    path('search',SearchName.as_view(),name="search"),
    path('searchname',Search,name="searchname"),

    path('addcourse',AddCourse.as_view(),name="addcourse"),
    path('courseupdate/<int:pk>',CourseUpdate.as_view(),name="courseupdate"),
    path('coursedelete/<int:pk>',CourseDelete.as_view(),name="coursedelete"),

    path('addbatch',AddBatch.as_view(),name="addbatch"),
    path('updatebatch/<int:pk>',BatchUpdate.as_view(),name="updatebatch"),
    path('deletebatch/<int:pk>',BatchDelete.as_view(),name="deletebatch"),
    path('batchreport/<int:pk>',BatchReport.as_view(),name="batchreport"),

    path('addcouncillor',AddCouncillor.as_view(),name="addcouncillor"),
    path('updatecouncillor/<int:pk>',CouncillorUpdate.as_view(),name="updatecouncillor"),
    path('deletecouncillor/<int:pk>',CouncillorDelete.as_view(),name="deletecouncillor"),

    path('newadmission/<str:pk>',NewAdmission.as_view(),name="newadmission"),
    path('payment/<str:pk>',PaymentDetails.as_view(),name="payment"),
    path('pay',Pay.as_view(),name="pay"),
    # path('admilist',Admission_list.as_view(),name="admilist"),

    path('',RegistrationPage.as_view(),name="registration"),
    path('login',LoginUser.as_view(),name="login"),
    path('logsout',logoutuser,name="logsout"),

    path('viewbatch',ViewBatch.as_view(),name="viewbatch"),
    path('viewbatchgo',ViewBatchOngoing.as_view(),name="viewbatchgo"),
]

enquiry/enquiry/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('enquiry/',include('enq.urls')),
    path('enquiry/',lambda request:render(request,"enq/base1.html"),name="index"),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

enquiry/enq/models.py
from django.db import models
from datetime import date
import uuid
from django.db import models


# Create your models here
class Course(models.Model):

    course_name=models.CharField(max_length=120,unique=True)
    course_duration=models.CharField(max_length=50)
    course_date=models.DateField()
    def __str__(self):
        return str(self.course_name)

class Batch(models.Model):

    Batch_code=models.CharField(max_length=120,unique=True)
    course_name=models.ForeignKey(Course,on_delete=models.CASCADE)
    Batch_Date=models.DateField()
    action=(('1','yet_to_begin'),
            ('2','started'),
            ('3','completed'))
    Batch_Status=models.CharField(max_length=120,choices=action)
    def __str__(self):
        return str(self.Batch_code)

class Councillor(models.Model):
    councillor_name=models.CharField(max_length=60)
    def __str__(self):
        return str(self.councillor_name)


class Enquiry(models.Model):
    enquiry_id= models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    student_name=models.CharField(max_length=120)
    address=models.CharField(max_length=250)
    qualification=models.CharField(max_length=120)
    college_name=models.CharField(max_length=120)
    course=models.ForeignKey(Course,on_delete=models.CASCADE)
    Batch_code=models.ForeignKey(Batch,on_delete=models.CASCADE)
    phone_no=models.IntegerField()
    email=models.EmailField()
    enquiry_date=models.DateField(default=date.today())
    followup_date=models.DateField()
    sourse=models.CharField(max_length=120)
    councillor=models.ForeignKey(Councillor,on_delete=models.CASCADE)

    action=(('1','call_back'),
            ('2','admitted'),
            ('3','cancel'))
    status=models.CharField(max_length=30,choices=action)
    def __str__(self):
        return str(self.enquiry_id)


class Admission(models.Model):
    admission_no=models.CharField(max_length=20,unique=True)
    student_name=models.CharField(max_length=120)
    enquiryid=models.CharField(max_length=50)
    coursefee=models.IntegerField()
    Batch_code=models.ForeignKey(Batch,on_delete=models.CASCADE)
    date=models.DateField(default=date.today())
    def __str__(self):
        return self.admission_no

class Payment(models.Model):
    admission_no=models.CharField(max_length=15)
    student_name = models.CharField(max_length=120)
    amount=models.IntegerField()
    cfee=models.ForeignKey(Admission,on_delete=models.CASCADE)
    payment_date=models.DateField(default=date.today())
    enquiryid=models.CharField(max_length=50)
    def __str__(self):
        return self.amount

enquiry/enq/views.py
from django.db.models import Count
# from itertools import count
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models import Sum
from django.core.paginator import Paginator
from enq.models import *
from enq.forms import *
# Create your views here.
from datetime import date
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView, TemplateView


from enq.models import *
class Home(TemplateView):
    template_name = "enq/home.html"


    #object_list=Enquiry.objects.all()
    #context={}
    #contect["object_list"]=object_list
    #return render (request, self.template_name,context)
# @method_decorator(login_required)
class RegistrationPage(TemplateView):
    model=User
    template_name = "reg/regis.html"
    form_class=CreateUserFrm()
    def get(self, request, *args, **kwargs):
        contex={}
        contex["form"]=self.form_class
        return render(request,self.template_name,contex)

    def post(self, request, *args, **kwargs):
        form=CreateUserFrm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("login")
        else:
            contex = {}
            contex["form"] = self.form_class
            return render(request, self.template_name, contex)
class LoginUser(TemplateView):
    model=User
    template_name = "reg/login.html"
    def get(self, request, *args, **kwargs):
        return render(request,self.template_name)
    def post(self, request, *args, **kwargs):
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(request,username=username,password=password)
        context={}

        if user is not None:
            login(request,user)
            return redirect("home")
        else:
            messages='incorrect username or password'
            context["messages"]=messages
        return render(request, self.template_name,context)


def logoutuser(request):
    logout(request)
    return redirect("login")

class AddCouncillor(TemplateView):
    model=Councillor
    template_name = "batch/councillor_add.html"
    form_class=CouncillorFrm
    def get(self, request, *args, **kwargs):
        qs=Councillor.objects.all()
        form=self.form_class
        context={}
        context["form"]=form
        context["councillor"]=qs
        return render(request,self.template_name,context)
    def post(self, request, *args, **kwargs):
        form=self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect("addcouncillor")
        else:
            context={}
            context[form]=form
            return render(request,self.template_name,context)

class CouncillorDelete(DeleteView):
    model = Councillor

    def get(self, request, *args, **kwargs):
        c_id = self.kwargs.get("pk")
        qs = Councillor.objects.get(id=c_id).delete()
        context = {}
        context["form"] = qs
        return redirect("addcouncillor")
class CouncillorUpdate(UpdateView):
    model=Councillor
    form_class = CourseUpdateFrm
    template_name = "batch/councillor_update.html"
    def get(self, request, *args, **kwargs):
        c_id=self.kwargs.get('pk')
        qs=Councillor.objects.get(id=c_id)
        form=self.form_class(instance=qs)
        context={}
        context["form"]=form
        return render(request,self.template_name,context)
    def post(self, request, *args, **kwargs):
        b_id = self.kwargs.get('pk')
        qs = Councillor.objects.get(id=b_id)
        form=self.form_class(request.POST,instance=qs)
        if form.is_valid():
            form.save()
            return redirect("addcouncillor")
        else:
            context = {}
            context["form"] = form
            return render(request, self.template_name, context)


class Enquiry_list(ListView):
    model = Enquiry
    template_name = "enq/enq_list.html"
    context_object_name = "enquiry"
    # def get(self, request, *args, **kwargs):
    #     qs = Enquiry.objects.filter(status="1,2")
    #     context={}
    #     context["enquiry"]=qs
    #     #
    #     return render(request,self.template_name,context)


# class  Enquiry_Create(CreateView):
#     model = Enquiry
#     form_class = EnquiryFrm
#     template_name = "enq/enq_create.html"
#     success_url = reverse_lazy("listenquiry")
#
#     @method_decorator(login_required)
#     def dispatch(self, request, *args, **kwargs):
#         return super(self.__class__, self).dispatch(request, *args, **kwargs)


class  Enquiry_Create(TemplateView):
    model = Enquiry
    form_class = EnquiryFrm
    template_name = "enq/enq_create.html"
    def get(self, request, *args, **kwargs):
        id = self.kwargs.get("pk")
        form=self.form_class(initial={'enquiryid': id})
        context={}
        context["form"]=form
        # context["id"]=id
        return render(request,self.template_name,context)
    def post(self, request, *args, **kwargs):
        # id = self.kwargs.get("pk")
        # qs = Enquiry.objects.get(enquiry_id=id)
        form=self.form_class(request.POST)
        if form.is_valid():
            en=form.save(commit=False)
            enquiry_id=en.enquiry_id
            # id = self.kwargs.get("pk")
            # qs=Enquiry.objects.filter(status='2')
            # qs = Enquiry.objects.get(enquiry_id=id)
            en.save()
            status=form.cleaned_data['status']
            if(status=='2'):
                return redirect('newadmission',pk=enquiry_id)
            else:
                return redirect('listenquiry')
        else:
            context={}
            context["form"]=form
            return render(request,self.template_name,context)



class EnquiryDetail(DetailView):
    model = Enquiry
    template_name = "enq/enq_details.html"
    context_object_name = "details"

    # details=Enquiry.objects.get(id=pk)
    # context={}
    # contect["object_list"]=object_list
    # return render (request, self.template_name,context)

class EnquiryUpdate(UpdateView):
    model = Enquiry
    form_class = EnquiryUpdateFrm
    template_name = "enq/enq_update.html"
    success_url = reverse_lazy("listenquiry")
    # def get(self, request, *args, **kwargs):
    #     e_id=self.kwargs.get('pk')
    #     qs=Course.objects.get(id=e_id)
    #     form=self.form_class(instance=qs)
    #     context={}
    #     context["form"]=form
    #     return render(request,self.template_name,context)
    # def post(self, request, *args, **kwargs):
    #     e_id = self.kwargs.get('pk')
    #     qs = Course.objects.get(id=e_id)
    #     form=self.form_class(request.POST,instance=qs)
    #     if form.is_valid():
    #         form.save()
    #         return redirect("listenquiry")
    #     else:
    #         context = {}
    #         context["form"] = form
    #         return render(request, self.template_name, context)
class EnquiryDelete(DeleteView):
    model = Enquiry
    form_class = EnquiryUpdateFrm
    template_name = "enq/enq_delete.html"
    success_url = reverse_lazy("listenquiry")
class FollowUp(TemplateView):
    model = Enquiry
    template_name = "enq/followups.html"

    def get_queryset(self):
        return Enquiry.objects.filter(followup_date= date.today(),status="1")
        # return Enquiry.objects.filter(status="1")
    def get(self, request, *args, **kwargs):
        context={}
        context["enquires"]=self.get_queryset()
        return render(request,self.template_name,context)

# class FollowUpDetail(TemplateView):
#     model = Enquiry
#     template_name = "enq/followupdetails.html"
#     form_class = EnquiryUpdateFrm
#     def get(self,request,*args,**kwargs):
#         id = self.kwargs.get('pk')
#         qs=Enquiry.objects.get(enquiry_id=id)
#         form=self.form_class(instance=qs)
#         context={}
#         context["form"]=form
#         return render(request,self.template_name,context)
#     def post(self,request,*args,**kwargs):
#         form=self.form_class(request.POST)
#         if(form.is_valid()):
#             form.save()
#             return redirect("followup")
#         else:
#             context = {}
#             context["form"] = form
#             return render(request, self.template_name,context)
class FollowUpDetail(UpdateView):
    model = Enquiry
    form_class = EnquiryUpdateFrm
    template_name = "enq/followupdetails.html"
    # success_url = reverse_lazy("followup")
    def get(self, request, *args, **kwargs):
        id=self.kwargs.get("pk")
        qs=Enquiry.objects.get(enquiry_id=id)
        form=self.form_class(instance=qs)
        context = {}
        context["form"]= form
        context["id"]=id
        return render(request,self.template_name,context)

    def post(self, request, *args, **kwargs):
        id=self.kwargs.get("pk")
        qs=Enquiry.objects.get(enquiry_id=id)
        form=self.form_class(request.POST,instance=qs)
        if form.is_valid():
            form.save()
            return redirect("followup")
        else:
            context = {}
            context["form"] = form
            return render(request, self.template_name, context)
# class SearchDate(TemplateView):
#     model=Enquiry
#     form_class=SearchDateFrm
#     template_name = "enq/followup_searchdate.html"
#     def get(self, request, *args, **kwargs):
#         form=self.form_class
#         context={}
#         context["form"]=form
#         return render(request,self.template_name,context)
#
#     def post(self, request, *args, **kwargs):
#         form=self.form_class(request.POST)
#         if(form.is_valid()):
#
#             dte=form.cleaned_data['followup_date']

enquiry/enq/templates/batch/batch_create.html
<!DOCTYPE html>
{% extends 'enq/base1.html' %}
{% block content %}
<style>
body{
color:#3b3d3b;
}
</style>
<div class="row ">
        <div class="col-lg"></div>
         <div class="col-lg">

<div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Create Batch</h6>
    </div>
        <div class="card-body">
            <div class="card-body">
          <div class="table-responsive1">
            <form method="post" >
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit">
            </form>
          </div>
            </div>
        </div>
</div>
     </div>
         <div class="col-lg"></div>
</div>

            <hr>
              <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Batch List</h6>
    </div>
        <div class="card-body">
            <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <tbody>
                    {% for data in batch %}
                    <tr>
                        <td>{{data.Batch_code}}</td>
                        <td>{{data.Batch_Date}}</td>
                        <td>{{data.get_Batch_Status_display}}</td>
                        <td><a href="{%url 'updatebatch' data.id%}" class="btn btn-success">Update</a> </td>
                        <td><a href="{%url 'batchreport' data.id%}" class="btn btn-success">Report</a></td>
                        <td><a href="{%url 'deletebatch' data.id%}" class="btn btn-success">Delete</a> </td>
                    </tr>
                    {% endfor %}<br><br>
                </tbody>
            </table><br><br>
          </div>
            </div>
        </div>
</div>
<input type=button class="btn btn-outline-warning" style="margin-top: 30px;" value="Back" onClick="javascript:history.go(-1);">

{% endblock %}

enquiry/enq/templates/batch/batch_update.html
<!DOCTYPE html>
{% extends 'enq/base1.html' %}
{% block content %}
<style>
body{
background-color: #d5f4e6;
font-family: font-effect-anaglyph;
        font-size: 20px;
}
</style>


    <div class="row">
        <div class="col-lg"></div>
        <div class="col-lg"><br><br><br>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-success" value="Update">


</form>
    </div>


    <div class="col-lg"></div>
    </div>
<input type=button class="btn btn-outline-warning" style="margin-top: 30px;" value="Back" onClick="javascript:history.go(-1);">

{% endblock %}

enquiry/enq/templates/batch/batchreport.html
<!DOCTYPE html>
{% extends 'enq/base1.html' %}
{% block content %}
<h4>{{form1.Batch_code__Batch_code}}</h4>
<table border="1px" class="table-dark">
    <thead>
    <tr>
        <th>Name</th>
        <th>Ph.No</th>
        <th>councillor</th>
    </tr>
    </thead>
    {% for data in form1 %}
    <tr>
            <td>{{data.student_name}}</td>
            <td>{{data.phone_no}}</td>
            <td>{{data.get_councillor_display}}</td>
    </tr><br>
    {% endfor %}<br>
</table>
<input type=button class="btn btn-outline-warning" style="margin-top: 30px;" value="Back" onClick="javascript:history.go(-1);">

{% endblock %}

enquiry/enq/templates/batch/coun_report.html
<!DOCTYPE html>
{% extends 'enq/base1.html' %}
{% block content %}
<style>
body{
color:#3b3d3b;
}
</style>
<div class="row">
    <div class="col-md"></div>
    <div class="col-md">
                    <h3><b><i>Counsellors Report</i></b></h3><br>

<table class="table table-dark">

    <tr class="bg-primary">

      <th>Name</th>
      <th>Call backs</th>
    </tr>
    {% for i in form0 %}
    <tr class="bg-primary">
      <td>{{i.councillor__councillor_name}}</td>
      <td>{{i.co}}</td>
    </tr>
    {% endfor %}
</table>


<hr>
<hr>

<table class="table table-dark">
    <tr class="bg-info">

      <th>Name</th>
      <th>Admitted</th>
    </tr>
    {% for j in form00 %}
    <tr class="bg-info">
      <td>{{j.councillor__councillor_name}}</td>
      <td>{{j.co2}}</td>
    </tr>
    {% endfor %}
</table>
</div>
    <div class="col-md"></div>

</div>
<input type=button class="btn btn-outline-warning" style="margin-top: 30px;" value="Back" onClick="javascript:history.go(-1);">

{% endblock %}

enquiry/enq/templates/batch/councillor_add.html
<!DOCTYPE html>
{% extends 'enq/base1.html' %}
{% block content %}
<style>
body{
color:#3b3d3b;
}
</style>


    <div class="row">
        <div class="col-lg"></div>
        <div class="col-lg">
            <h3><b><i>Counsellors</i></b></h3><br>

<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Create">
</form>
<hr>
<table border="1px" class="table-dark"><hr>
    {% for data in councillor %}
    <tr>
        <td>{{data.councillor_name}}</td>
        <td><a href="{%url 'updatecouncillor' data.id%}" class="btn btn-success">Update</a> </td>
        <td><a href="{%url 'deletecouncillor' data.id%}" class="btn btn-success">Delete</a> </td>
    </tr>
    {% endfor %}
</table>
         </div>


    <div class="col-lg"></div>
    </div>
<input type=button class="btn btn-outline-warning" style="margin-top: 30px;" value="Back" onClick="javascript:history.go(-1);">

{% endblock %}

enquiry/enq/templates/batch/councillor_update.html
<!DOCTYPE html>
{% extends 'enq/base1.html' %}
{% block content %}
<style>
body{
color:#3b3d3b;
}
</style>


    <div class="row">
        <div class="col-lg"></div>
        <div class="col-lg">
                        <h3><b><i>Counsellors</i></b></h3><br>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-success" value="Update">


</form>
    </div>


    <div class="col-lg"></div>
    </div>
<input type=button class="btn btn-outline-warning" style="margin-top: 30px;" value="Back" onClick="javascript:history.go(-1);">

{% endblock %}

enquiry/enq/templates/batch/viewbatch.html
<!DOCTYPE html>
{% extends 'enq/base1.html' %}
{% block content %}
<style>
body{
color:#3b3d3b;
}
</style>

<h3 align="center"><b><i>Batch report (Yet to begin)</i></b></h3><br>
    <div class="row">
        {% for j in form %}
        <div class="col-md-4">
    <table border="1px">
    <tr>
        <td>Batch</td><td>{{j.Batch_code__Batch_code}}</td>
    </tr>
    <tr>
        <td>Course</td><td>{{j.Batch_code__course_name__course_name}}</td>
    </tr>
    <tr>
        <td>Batch Date</td><td>{{j.Batch_code__Batch_Date}}</td>
    </tr>
    <tr>
        <td>Admitted</td><td>{{j.enqadmitted11}}</td>
    </tr>
    <tr>
        <td>Total Revenue</td><td>{{j.fee}}</td>
    </tr>
        </table><br>
        </div>
        {% endfor %}
    <div class="col-md-4"></div>
    <div class="col-md-4"></div>
    <div class="col-md-4"></div>
    </div>
<table>

</table>
<input type=button class="btn btn-outline-warning" style="margin-top: 30px;" value="Back" onClick="javascript:history.go(-1);">

{% endblock %}

enquiry/enq/templates/batch/viewbatch2.html
<!DOCTYPE html>
{% extends 'enq/base1.html' %}
{% block content %}
<style>
body{
color:#3b3d3b;
}
</style>

<h3 align="center"><b><i>Batch report (on going)</i></b></h3><br>
    <div class="row">
        {% for j in form %}
        <div class="col-md-4">
    <table border="1px" class="table-dark">
    <tr>
        <td>Batch</td><td>{{j.Batch_code__Batch_code}}</td>
    </tr>
    <tr>
        <td>Course</td><td>{{j.Batch_code__course_name__course_name}}</td>
    </tr>
    <tr>
        <td>Batch Date</td><td>{{j.Batch_code__Batch_Date}}</td>
    </tr>
    <tr>
        <td>Admitted</td><td>{{j.enqadmitted11}}</td>
    </tr>
    <tr>
        <td>Total Revenue</td><td>{{j.fee}}</td>
    </tr>
        </table><br>
        </div>
        {% endfor %}
    <div class="col-md-4"></div>
    <div class="col-md-4"></div>
    <div class="col-md-4"></div>
    </div>
<table>

</table>
<input type=button class="btn btn-outline-warning" style="margin-top: 30px;" value="Back" onClick="javascript:history.go(-1);">

{% endblock %}